CREATE TABLE IF NOT EXISTS personnel (
  id INT PRIMARY KEY AUTO_INCREMENT,
  institute_id INT NOT NULL,
  teachers_phd INT DEFAULT 0,
  teachers_master INT DEFAULT 0,
  teachers_bachelor INT DEFAULT 0,
  technical_phd INT DEFAULT 0,
  technical_master INT DEFAULT 0,
  technical_bachelor INT DEFAULT 0,
  technical_above_baccalaureate INT DEFAULT 0,
  technical_baccalaureate INT DEFAULT 0,
  technical_elementary INT DEFAULT 0,
  admin_phd INT DEFAULT 0,
  admin_master INT DEFAULT 0,
  admin_bachelor INT DEFAULT 0,
  admin_above_baccalaureate INT DEFAULT 0,
  admin_baccalaureate INT DEFAULT 0,
  admin_elementary INT DEFAULT 0,
  service_bachelor INT DEFAULT 0,
  service_above_baccalaureate INT DEFAULT 0,
  service_baccalaureate INT DEFAULT 0,
  service_elementary INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (institute_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_institute (institute_id)
); 