CREATE TABLE IF NOT EXISTS vision_mission (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vision TEXT NOT NULL,
    mission TEXT NOT NULL,
    strategic_goals TEXT NOT NULL,
    userId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 